// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// discreteLV_C
NumericMatrix discreteLV_C(NumericMatrix r_, NumericMatrix alphas_, NumericVector ntmp_, double deltat, int simtime);
RcppExport SEXP predictimportance_discreteLV_C(SEXP r_SEXP, SEXP alphas_SEXP, SEXP ntmp_SEXP, SEXP deltatSEXP, SEXP simtimeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type r_(r_SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type alphas_(alphas_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ntmp_(ntmp_SEXP);
    Rcpp::traits::input_parameter< double >::type deltat(deltatSEXP);
    Rcpp::traits::input_parameter< int >::type simtime(simtimeSEXP);
    __result = Rcpp::wrap(discreteLV_C(r_, alphas_, ntmp_, deltat, simtime));
    return __result;
END_RCPP
}
