# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate a discrete-time Lotka-Volterra time series in C
#'
#' Simulate discrete-time Lotka-Volterra population dynamics
#' with perturbed growth rates
#'
#' @param rmat a matrix with S (number of species) rows and simtime
#' cols containing the growth rates at each time step (potentially
#' perturbed at each time step) 
#' @param alphas an S by S matrix of per capita interaction strengths
#' @param n0s a vector of length S containing species abundances
#' @param deltat the size of the time step
#' @param simtime the total number of time steps to simulate
#'
#' @return an S by simtime matrix of species abundances at each timestep
#' @export
discreteLV_C <- function(r_, alphas_, ntmp_, Is_, deltat, simtime) {
    .Call('predictimportance_discreteLV_C', PACKAGE = 'predictimportance', r_, alphas_, ntmp_, Is_, deltat, simtime)
}

